# Generated by Django 5.1.4 on 2025-01-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_post_rename_submitter_comment_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
